### Week 3 Lab
## Cleaning and Storing Data

#### Import Packages

In [6]:
#Importing required packages 

#import seaborn as sns
#import pandas as pd
#import numpy as np

In [59]:
#from sqlalchemy import create_engine

### Getting data details

#### Connection Variables

In [12]:
host = r'127.0.0.1'
db = r'MSDS610'
user = r'postgres'
pw = r'Pa55w0rd'
port = r'5432'
schema = r'raw'

#### Connection to DB and Retrieving Data

In [14]:
db_conn = create_engine("postgresql://{}:{}@{}:{}/{}".format(user, pw, host, port, db))

In [23]:
table_name = r'sales_transaction'
schema = r'raw'

In [29]:
df = pd.read_sql_table(table_name, db_conn, schema)

#### Looking at Data

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536350 entries, 0 to 536349
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Date         536350 non-null  object
 1   ProductNo    536350 non-null  object
 2   ProductName  536350 non-null  object
 3   Price        536350 non-null  float64
 4   Quantity     536350 non-null  int64
 5   CustomerNo   536295 non-null  float64
 6   Country      536350 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 28.6+ MB

In [39]:
df.head(10)

,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
0,12/9/2019,22485,Set Of 2 Wooden Market Crates,21.47,12,17490.0,United Kingdom
1,12/9/2019,22596,Christmas Star Wish List Chalkboard,10.65,36,13069.0,United Kingdom
2,12/9/2019,23235,Storage Tin Vintage Leaf,11.53,12,13069.0,United Kingdom
3,12/9/2019,23272,Tree T-Light Holder Willie Winkie,10.65,12,13069.0,United Kingdom
4,12/9/2019,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6,13069.0,United Kingdom
5,12/9/2019,21705,Bag 500g Swirly Marbles,10.65,24,13069.0,United Kingdom
6,12/9/2019,22118,Joy Wooden Block Letters,11.53,18,13069.0,United Kingdom
7,12/9/2019,22119,Peace Wooden Block Letters,12.25,12,13069.0,United Kingdom
8,12/9/2019,22217,T-Light Holder Hanging Lace,10.65,12,13069.0,United Kingdom
9,12/9/2019,22216,T-Light Holder White Lace,10.55,24,13069.0,United Kingdom

### Cleaning Data

#### Account for missing values

In [46]:
df.replace([None], np.nan, inplace=True)

In [93]:
clean_df = df.copy()

In [95]:
clean_df.CustomerNo.unique()

array([17490., 13069., 12433., ..., 13065., 18011., 17558.])

In [97]:
clean_df[clean_df.CustomerNo.isna()]

,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
6511,12/8/2019,46000M,Polyester Filler Pad 45x45cm,6.19,-240,NaN,United Kingdom
6512,12/8/2019,46000S,Polyester Filler Pad 40x40cm,6.19,-300,NaN,United Kingdom
90211,11/8/2019,22947,Wooden Advent Calendar Red,44.25,-1,NaN,United Kingdom
102801,11/3/2019,22178,Victorian Glass Hanging T-Light,25.37,-1,NaN,United Kingdom
117410,10/28/2019,23048,Set Of 10 Lanterns Fairy Light Star,14.50,-1,NaN,United Kingdom
163290,10/4/2019,21843,Red Retrospot Cake Stand,21.47,-1,NaN,United Kingdom
190703,9/20/2019,22846,Bread Bin Diner Style Red,27.62,-1,NaN,United Kingdom
192389,9/20/2019,21871,Save The Planet Mug,11.94,-12,NaN,United Kingdom
242470,8/11/2019,46000M,Polyester Filler Pad 45x45cm,10.25,-160,NaN,United Kingdom
242471,8/11/2019,46000S,Polyester Filler Pad 40x40cm,10.25,-220,NaN,United Kingdom
246391,8/8/2019,23243,Set Of Tea Coffee Sugar Tins Pantry,15.32,-2,NaN,United Kingdom
254294,8/1/2019,22371,Airline Bag Vintage Tokyo 78,14.48,-1,NaN,United Kingdom
254298,8/1/2019,84595E,Large Tortilla Design Red Bowl,13.62,-1,NaN,United Kingdom
260673,7/26/2019,22427,Enamel Flower Jug Cream,16.35,-1,NaN,United Kingdom
260674,7/26/2019,22426,Enamel Wash Bowl Cream,14.09,-1,NaN,United Kingdom
260675,7/26/2019,84755,Colour Glass T-Light Holder Hanging,10.92,-4,NaN,United Kingdom
276405,7/14/2019,22699,Roses Regency Teacup And Saucer,13.27,-2,NaN,United Kingdom
285497,7/7/2019,23001,Travel Card Wallet Dotcomgiftshop,10.25,-200,NaN,United Kingdom
285498,7/7/2019,22616,Pack Of 12 London Tissues,10.25,-204,NaN,United Kingdom
285499,7/7/2019,23298,Spotty Bunting,10.25,-170,NaN,United Kingdom
297263,6/28/2019,22960,Jam Making Set With Jars,18.75,-1,NaN,United Kingdom
298357,6/27/2019,22734,Set Of 6 Ribbons Vintage Christmas,10.25,8,NaN,United Kingdom
303174,6/21/2019,22847,Bread Bin Diner Style Ivory,25.57,-1,NaN,United Kingdom
304644,6/21/2019,23183,Mother's Kitchen Spoon Rest,14.09,-1,NaN,United Kingdom
311959,6/15/2019,46000M,Polyester Filler Pad 45x45cm,10.25,-80,NaN,United Kingdom
311960,6/15/2019,46000S,Polyester Filler Pad 40x40cm,10.25,-160,NaN,United Kingdom
333759,5/26/2019,22662,Lunch Bag Dolly Girl Design,5.97,-1,NaN,United Kingdom
333760,5/26/2019,23206,Lunch Bag Apple Design,5.97,-1,NaN,United Kingdom
342940,5/19/2019,84945,Multi Colour Silver T-Light Holder,21.28,-1,NaN,United Kingdom
342986,5/19/2019,22053,Empire Design Rosette,11.53,-1,NaN,United Kingdom
342987,5/19/2019,21703,Bag 125g Swirly Marbles,10.68,-1,NaN,United Kingdom
342988,5/19/2019,22891,Tea For One Polkadot,14.61,-1,NaN,United Kingdom
361528,5/6/2019,20735,Black Mini Tape Measure,10.25,-1,NaN,United Kingdom
361529,5/6/2019,22617,Baking Set Spaceboy Design,10.25,-1,NaN,United Kingdom
361530,5/6/2019,37327,Asstd Multicolour Circles Mug,10.25,-1,NaN,United Kingdom
361531,5/6/2019,84375,Set Of 20 Kids Cookie Cutters,10.25,-1,NaN,United Kingdom
361532,5/6/2019,84969,Box Of 6 Assorted Colour Teaspoons,10.25,-1,NaN,United Kingdom
395848,4/1/2019,22453,Measuring Tape Babushka Blue,13.27,-1,NaN,United Kingdom
412515,3/20/2019,22766,Photo Frame Cornice,13.27,-12,NaN,United Kingdom
412516,3/20/2019,21316,Small Chunky Glass Roman Bowl,13.27,-1,NaN,United Kingdom
412517,3/20/2019,22800,Antique Tall Swirlglass Trinket Pot,14.09,-4,NaN,United Kingdom
413876,3/18/2019,22567,20 Dolly Pegs Retrospot,11.53,-1,NaN,United Kingdom
416793,3/16/2019,22212,Four Hook White Lovebirds,12.40,-1,NaN,United Kingdom
429813,3/3/2019,22907,Pack Of 20 Napkins Pantry Design,11.12,-12,NaN,United Kingdom
454103,2/7/2019,48173C,Doormat Black Flock,18.40,-1,NaN,United Kingdom
455578,2/4/2019,22333,Retrospot Party Bag + Sticker Set,11.94,-14,NaN,United Kingdom
455579,2/4/2019,22332,Skulls Party Bag + Sticker Set,11.94,-14,NaN,United Kingdom
459493,2/1/2019,22580,Advent Calendar Gingham Sack,16.35,-1,NaN,United Kingdom
462664,1/28/2019,21658,Glass Beurre Dish,18.75,-1,NaN,United Kingdom
483239,1/12/2019,22461,Savoy Art Deco Clock,23.32,-1,NaN,United Kingdom
486691,1/10/2019,21888,Bingo Set,14.09,-4,NaN,United Kingdom
493070,1/5/2019,72802B,Ocean Scent Candle In Jewelled Box,14.16,-54,NaN,United Kingdom
495235,12/23/2018,21888,Bingo Set,14.09,-4,NaN,United Kingdom
497089,12/21/2018,22720,Set Of 3 Cake Tins Pantry Design,15.32,-1,NaN,United Kingdom
507570,12/14/2018,22467,Gumball Coat Rack,12.86,-1,NaN,United Kingdom

In [99]:
df_missing = clean_df[clean_df.CustomerNo.isna()].copy()

In [101]:
df_missing.head(10)

,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
6511,12/8/2019,46000M,Polyester Filler Pad 45x45cm,6.19,-240,NaN,United Kingdom
6512,12/8/2019,46000S,Polyester Filler Pad 40x40cm,6.19,-300,NaN,United Kingdom
90211,11/8/2019,22947,Wooden Advent Calendar Red,44.25,-1,NaN,United Kingdom
102801,11/3/2019,22178,Victorian Glass Hanging T-Light,25.37,-1,NaN,United Kingdom
117410,10/28/2019,23048,Set Of 10 Lanterns Fairy Light Star,14.50,-1,NaN,United Kingdom
163290,10/4/2019,21843,Red Retrospot Cake Stand,21.47,-1,NaN,United Kingdom
190703,9/20/2019,22846,Bread Bin Diner Style Red,27.62,-1,NaN,United Kingdom
192389,9/20/2019,21871,Save The Planet Mug,11.94,-12,NaN,United Kingdom
242470,8/11/2019,46000M,Polyester Filler Pad 45x45cm,10.25,-160,NaN,United Kingdom
242471,8/11/2019,46000S,Polyester Filler Pad 40x40cm,10.25,-220,NaN,United Kingdom

#### Replacing missing customer numbers with 0

In [103]:
df_missing['CustomerNo'].fillna(0, inplace=True)

In [105]:
df_missing.head(10)

,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
6511,12/8/2019,46000M,Polyester Filler Pad 45x45cm,6.19,-240,0.0,United Kingdom
6512,12/8/2019,46000S,Polyester Filler Pad 40x40cm,6.19,-300,0.0,United Kingdom
90211,11/8/2019,22947,Wooden Advent Calendar Red,44.25,-1,0.0,United Kingdom
102801,11/3/2019,22178,Victorian Glass Hanging T-Light,25.37,-1,0.0,United Kingdom
117410,10/28/2019,23048,Set Of 10 Lanterns Fairy Light Star,14.50,-1,0.0,United Kingdom
163290,10/4/2019,21843,Red Retrospot Cake Stand,21.47,-1,0.0,United Kingdom
190703,9/20/2019,22846,Bread Bin Diner Style Red,27.62,-1,0.0,United Kingdom
192389,9/20/2019,21871,Save The Planet Mug,11.94,-12,0.0,United Kingdom
242470,8/11/2019,46000M,Polyester Filler Pad 45x45cm,10.25,-160,0.0,United Kingdom
242471,8/11/2019,46000S,Polyester Filler Pad 40x40cm,10.25,-220,0.0,United Kingdom

In [108]:
clean_df = clean_df.combine_first(df_missing)

In [112]:
clean_df[clean_df.CustomerNo.isna()]

Empty DataFrame
Columns: [Date, ProductNo, ProductName, Price, Quantity, CustomerNo, Country]
Index: []